### ISSUE TITLE
Hardcoded build_variant

### ISSUE THREAD

**Issue by Aksi0m** [Guardsquare/bitrise-step-scan-with-appsweep#1]
Current `build_variant` field seems useless since it is hardcoded to run either `uploadToAppSweepDebug` `uploadToAppSweepRelease ` variants. Can we change that to run custom build variants, since most projects will probably have custom variants.

**Comment by talhahasanzia** [comment]
Yes the only option is to select `debug` which runs `uploadToAppSweepDebug` and `release` which runs `uploadToAppSweepRelease`.

I have `prodRelease` variant and I cant even run it, seems like only fix for now for me is `Gradle Runner` step.

I have also tried setting an environment variable to `prodRelease` in `variant` option in step but it is still useless. I was expecting it will  replace `release` with `prodRelease`, but no luck.

**Comment by DoHuberGS** [comment]
Hey there, thanks for the feedback! We'll add support for custom build variants in #7.

**Comment by DoHuberGS** [comment]
PR to the main bitrise StepLib was just merged, closing this issue.
