### ISSUE TITLE
Custom build variant like `prodDebug` / `prodRelease` cannot be set 

### ISSUE THREAD

**Issue by talhahasanzia** [Guardsquare/bitrise-step-scan-with-appsweep#3]
The step has only option is to select `debug` which runs `uploadToAppSweepDebug` and `release` which runs `uploadToAppSweepRelease`.

I have `prodRelease` variant and I cant even run it, seems like only fix for now for me is `Gradle Runner` step.

I have also tried setting an environment variable to `prodRelease` in variant option in step but it is still useless. I was expecting it will replace `release` with `prodRelease`, but no luck.

**Comment by DoHuberGS** [comment]
Duplicate of #1 
Fix coming soon, stay tuned!

**Comment by DoHuberGS** [comment]
Wrong close status
